---
title: "dplyr-and-tidyr--lab-2023"
author: "Yufeng JIANG"
format: html
---

```{r}
#| message: false
here::i_am("dplyr-and-tidyr--lab-2023.Rproj")
library(here)
library(vroom)
library(ggplot2)
library(tidyr)
library(dplyr)
theme_set(theme_bw())
```
# Exercise 1

## Q1
```{r}
#| message: false
spotify <- vroom(here("data", "top-spotify-songs-from-20102019-by-year.csv"))
```
## Q2
Number of songs
```{r}
spotify |> 
  distinct(title) |>
  nrow()
```

Number of artists
```{r}
spotify |>
  distinct(artist) |>
  nrow()
```

Number of genres
```{r}
spotify |>
  distinct(`top genre`) |>
  nrow()
```
## Q3
```{r}
spotify |>
  group_by(year) |>
  summarise(n = n())
```
## Q4
```{r}
spotify |>
  group_by(artist) |>
  distinct(title) |>
  summarise(n = n()) |>
  arrange(-n) |>
  slice(1)
```
## Q5
```{r}
spotify |>
  distinct(title, .keep_all = TRUE) |>
  group_by(`top genre`) |>
  summarise(min = min(bpm),
            max = max(bpm),
            mean = mean(bpm),
            median = median(bpm),
            n = n())
```

# Exercise 2

## Q1
```{r}
#| message: false
grades <- vroom(here("data", "grades.csv"))
```
## Q2
```{r}
grades |>
  summarise(min = min(Exam, na.rm = TRUE),
            max = max(Exam, na.rm = TRUE),
            median = median(Exam, na.rm = TRUE),
            mean = round(mean(Exam, na.rm = TRUE), 2))
```
## Q3
```{r}
grades |>
  filter(is.na(Exam))
```
## Q4
```{r}
grades |>
  group_by(Group) |>
  distinct(Id) |>
  summarise(n = n())
```
```{r}
grades %>%
group_by(Group) %>%
summarise(nb_students = n())
```
## Q5
```{r}
grades |>
  group_by(Group) |>
  summarise(missed = sum(is.na(Exam)))
```



